name: Go CI Pipeline

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Install dependencies
      run: go mod tidy

    - name: Build main module
      run: go build -v ./...

    - name: Run tests for all modules
      run: |
        for dir in $(find . -type d -name 'go-*'); do
          echo "Running tests in $dir"
          go test -v $dir/...
        done